# Generated by Django 2.2.6 on 2019-10-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_auto_20191014_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
