# Generated by Django 2.2.6 on 2019-10-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_profile_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
